export const ADD_HEMISPHERE = 'ADD_HEMISPHERE';
export const REMOVE_HEMISPHERE = 'REMOVE_HEMISPHERE';
export const ADD_MARKER = 'ADD_MARKER';
export const REMOVE_MARKER = 'REMOVE_MARKER';
export const SET_MARKERS = 'SET_MARKERS';
export const DELETE_MARKERS = 'DELETE_MARKERS';
export const SET_MAP = 'SET_MAP';
